// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4kC2JjZ6_LITXVsDONcDMjFqQotAH0-E',
    appId: '1:494497732292:web:060a272edc7f7ef9311b91',
    messagingSenderId: '494497732292',
    projectId: 'final-project-c49b5',
    authDomain: 'final-project-c49b5.firebaseapp.com',
    storageBucket: 'final-project-c49b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZW4D4izM2a2KchxzJyx-xwmOGQXDaBKM',
    appId: '1:494497732292:android:f061b5426a97a5ad311b91',
    messagingSenderId: '494497732292',
    projectId: 'final-project-c49b5',
    storageBucket: 'final-project-c49b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQqoq2W3pFxdnXIieC6TNNWQxjJjy1jYY',
    appId: '1:494497732292:ios:5c1a391068702029311b91',
    messagingSenderId: '494497732292',
    projectId: 'final-project-c49b5',
    storageBucket: 'final-project-c49b5.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQqoq2W3pFxdnXIieC6TNNWQxjJjy1jYY',
    appId: '1:494497732292:ios:d20a52a51e0b551d311b91',
    messagingSenderId: '494497732292',
    projectId: 'final-project-c49b5',
    storageBucket: 'final-project-c49b5.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
